QE-7641: Use latest vault action version

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -19,16 +19,14 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v2
 
-      - name: bump version
-        uses: actions/setup-node@v2
-        with:
-          node-version: '14'
-      - run: npm --no-git-tag-version version patch > ${{github.workspace}}/version
-
-      - name: push to github
+      - name: bump version and push to github
         run: |
           git config user.email QualityEngineering@gannett.com
           git config user.name quality-engineering
+          npm --no-git-tag-version version patch > ${{github.workspace}}/version
+          echo "PACKAGE_VERSION=$( cat package.json | jq -r '.version' )" >> $GITHUB_ENV
+          git add package.json package-lock.json || { echo 'failed to update the index of package*.json' ; exit 1; }
+          git commit -m "[skip ci] ${PACKAGE_NAME} version bump"
           retryCount=0
           until [ "$n" -ge 5 ]
           do
